# Generated by Django 5.1.2 on 2025-11-13 14:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('capacity_ml', models.PositiveIntegerField(default=2000)),
                ('threshold_pct', models.FloatField(default=20.0)),
                ('status', models.CharField(default='ONLINE', max_length=16)),
                ('instalation_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField()),
                ('level_pct', models.FloatField()),
                ('level_ml', models.FloatField(blank=True, null=True)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='core.device')),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['device', 'ts'], name='core_teleme_device__b3a703_idx')],
            },
        ),
    ]
